### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yhardbe** [albertyablonskyi/cicflowmeter-py#1]
hello! I just input a pacp, but no result. What type of pacp file can I ask as input? If you answer, thank you! 
![image](https://github.com/albertyablonskyi/cicflowmeter-py/assets/45647203/bc91d50e-7f95-4fa3-9801-c576003f99b8)

**Comment by albertyablonskyi** [comment]
Hi there! First of all, I want to thank you for giving my fork of the program a try. Regarding the issue you're facing, it's possible that the 1000 packets you captured may not be sufficient to process even a single flow. In my experience, this sometimes happens, but I usually use the interface mode, which allows me to capture several thousand packets. With a larger sample size, I can process them into a few hundred flows.

I would also suggest considering the original version of the cicflowmeter. The version I forked was customized to meet the specific needs of my project and could potentially be causing the problems you're encountering.

Wishing you the best of luck, and I hope you find success! :)
